name: Bookeasy Frontend Customers UI (Build & Test)

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: .

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Build Env
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 15.x # Node version to use.
        check-latest: true # Latest version satisfying the above version constraint.
    - name: Install NPM Dependencies
      run: npm install
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Build
      run: npx react-scripts build
      working-directory: ${{env.WORKING_DIRECTORY}}
    - name: Test
      run: npx react-scripts test
      working-directory: ${{env.WORKING_DIRECTORY}}
